CC = cc
C_FLAGS = -DHAVE_XPM -Wall -O1 -I/usr/X11R6/include
L_FLAGS = -L/usr/X11R6/lib -lX11 -lXpm
PROGNAME = craftbar

$(PROGNAME): Makefile craftbar.c craftbar.h icon.xpm
	$(CC) $(C_FLAGS) $(L_FLAGS) craftbar.c -o $(PROGNAME)
	strip $(PROGNAME)
	@ls -l $(PROGNAME)

clean: 
	rm -f core *.o $(PROGNAME) nohup.out

install: $(PROGNAME)
	cp $(PROGNAME) /usr/local/bin
