CC = gcc
C_FLAGS = -DHAVE_XPM -Wall -O1 -I/usr/X11R6/include -m386 -malign-loops=2 -malign-jumps=2 -malign-functions=2
L_FLAGS = -Xlinker -s -L/usr/X11R6/lib -lX11 -lXpm
PROGNAME = craftbar

$(PROGNAME): Makefile craftbar.c craftbar.h icon.xpm
	$(CC) $(C_FLAGS) $(L_FLAGS) craftbar.c -o $(PROGNAME)
	@ls -l $(PROGNAME)

clean: 
	rm -f core *.o $(PROGNAME) nohup.out

install: $(PROGNAME)
	cp $(PROGNAME) /usr/local/bin
